### ISSUE TITLE
Add some traditional ligatures (e.g.: Fl fl Tl)

### ISSUE THREAD

**Issue by ExE-Boss** [microsoft/cascadia-code#114]
## Description of the new feature/enhancement (with images if possible)

The following character combinations should probably have ligatures:
<code>![Fl	fl	Tl](https://user-images.githubusercontent.com/3889017/65522321-e1971800-deea-11e9-9004-37e541fb4ee3.png)</code>

## Proposed technical implementation details (optional)

Create ligatures for the above character combinations, like what [**Fira Code**](https://github.com/tonsky/FiraCode) does:
[![](https://raw.githubusercontent.com/tonsky/FiraCode/master/showcases/all_ligatures.png)](https://github.com/tonsky/FiraCode/blob/master/showcases/all_ligatures.png)

**Comment by aaronbell** [comment]
What is the specific use in code of the Fl, Tl, and fl ligatures? Or are these just for looks?

**Comment by ExE-Boss** [comment]
These are primary for looks, since `l`’s serif touches the top‑rightmost bit of the letters `F`, `T` and `f`.

**Comment by aaronbell** [comment]
Ah ok. Looks like there's actually a gap between the letters (there's even a gap in the Fira Mono example). As such, I don't think a ligature is actually necessary. My general preference is to not add letter ligatures for purely aesthetic reasons, and rather only add them when there is actual collision. Otherwise, it can become distracting element in text, and gets all sorts of ugly should someone increase space between letters.

**Comment by aaronbell** [comment]
Closing as unnecessary :)
