### ISSUE TITLE
Incorrectly rendered in Jetbrains Webstorm 2019.2.3

### ISSUE THREAD

**Issue by mslourens** [microsoft/cascadia-code#150]
# Environment

```none
Cascadia Code version number: 1910.04
Application (with version) used to display text: Jetbrains Webstorm 2019.2.3
OS platform and version: Windows 10
Screen resolution (i.e. 220dpi): 3840x2160

Any other software?
```

# Steps to reproduce
Change the font setting in Webstorm to use Cascadia Code

# Expected behavior
The text of the opened files should be rendered in a readable format

# Actual behavior
Almost only strange characters are rendered (see attached screenshot)

Cascadia Code rendered in Webstorm:
![cascadio_code_webstorm](https://user-images.githubusercontent.com/1907152/66432932-7cc9da80-ea1f-11e9-864d-9e813968dbb5.png)

Cascadia Code rendered in VSCode:
![cascadio_code_vscode](https://user-images.githubusercontent.com/1907152/66432881-5e63df00-ea1f-11e9-9c7b-fb26671fa1b2.png)

**Comment by aaronbell** [comment]
I'm not able to repro this bug on my device.

<img width="688" alt="webbrains" src="https://user-images.githubusercontent.com/8460297/66447442-1afb7780-ea03-11e9-9e7b-c425a337a2e0.PNG">

It looks like there's some really weird swapping happening. Can you try uninstalling the font, redownloading, and re-installing? It might also be worth checking your customization in Webstorm.

**Comment by aaronbell** [comment]
This may also be related to: https://github.com/microsoft/terminal/issues/2979

**Comment by DHowett-MSFT** [comment]
I dunno? On account of the version in Terminal is the same as the one in this repository, it isn’t likely to be why Webstorm/Goland aren’t happy with it.

**Comment by aaronbell** [comment]
@mslourens Do you have a version of Terminal installed? And which version is it? 

If he hasn't updated, it could be an older version that still has the older version, I wonder.

**Comment by ForNeVeR** [comment]
These bugs usually happen when there're multiple versions of same font installed in the system.

1. It could happen if you have both TTF and OTF versions of the same font
2. It could happen if you have multiple versions of the same TTF font, which could happen in this case:
  - you have some program that uses the font
  - you're trying to update the font
  - Windows is unable to do that (because the font file is still open), so it leaves the old file forever
  - the updated font gets installed with the new name (e.g. `Cascadia_1.ttf`, something like that)
3. It could happen if the Windows font cache is corrupted (extremely rare, I wasn't able to observe that in the wild and only causes in specific circumstances in my lab environment)

How to fix that issue:

1. Check if you have multiple system-wide installations of the font: `dir C:\Windows\Fonts\Cascad*`
2. Check if you have multiple user-specific installations of the font: `dir %LOCALAPPDATA%\Microsoft\Windows\Fonts\Cascadia*`
  (if you have **both** system-wide and the user-specific font, it could cause the issue, too; please report such cases to JetBrains)
3. If everything seems okay but the font still looks wrong, you could try to [flush the Windows Font Cache](https://www.thewindowsclub.com/rebuild-font-cache-in-windows)

If the issue still persists, please tell JetBrains about that (preferably in a new YouTrack ticket).

In any case, nothing's wrong with the font itself: it is either an OS issue (with Windows Font Cache) or a JetBrains IDE / runtime issue. It is non-actionable from the font authors side.

**Comment by mslourens** [comment]
@ForNeVeR the steps you provided fixed the issue! Thanx all for your quick response. I will close the issue now.

**Comment by Sherlock-Holo** [comment]
@ForNeVeR I try to delete `Cascadia.ttf` and `Cascadia_0.ttf` from `%LOCALAPPDATA%\Microsoft\Windows\Fonts\` , it says **system** is using it.
How can I do to delete them

**Comment by ForNeVeR** [comment]
@Sherlock-Holo, first of all: have you deleted the fonts in the "official" way, via Windows Fonts directory? After you've done that, they sometimes will delete automatically after restart. And sometimes you'll be able to delete them manually after system restart.

**Comment by Sherlock-Holo** [comment]
@ForNeVeR I can't see this font in windows/fonts directory [here](https://github.com/microsoft/cascadia-code/issues/145#issuecomment-539386889)

and I found it in `%LOCALAPPDATA%\Microsoft\Windows\Fonts\`

**Comment by Sherlock-Holo** [comment]
I delete the font, uninstall windows terminal from UWP setting and reboot and install again, it works well now

**Comment by miloush** [comment]
Any idea how having multiple versions of a font results in the mess in OP's screenshot?

**Comment by ForNeVeR** [comment]
This is due to a bug in JVM font handling. As far as I understand it while debugging the issue, it somehow messes up the font metadata and the actual font glyphs: it uses the metadata from one font version, and the glyphs from another one, and they rarely match up.
