### ISSUE TITLE
Bad readability when used with "bold" decoration

### ISSUE THREAD

**Issue by TipaRiordan** [microsoft/cascadia-code#163]
# Environment

Cascadia Code version number: 1910.04
Application (with version) used to display text: CMD.EXE
OS platform and version: Windows 10 Pro, 10.0.18362.175
Screen resolution (i.e. 220dpi): 1600x1200 
Any other software?

# Steps to reproduce

Open CMD.EXE settings, 
change font to "Cascadia Code" (16), 
check "BOLD"
[OK]

# Expected behavior

Bold text should be (mostly) as easy to read as regular text.

# Actual behavior

Bold text is much harder to read than regular text, i.e. "w" is close to a compact rectangle:
![Regular_and_Bold](https://user-images.githubusercontent.com/46349551/67365099-3cb33d80-f571-11e9-9760-811fee69704e.png)

**Comment by kdien** [comment]
+1 for this! I understand, like other fonts, with the lack of a specific Bold variant, Windows basically just adds thickness to the font wherever it needs to be Bold. I'd much rather it do nothing instead of this.
Interesting thing is that the same situation is handled much much better in Linux where it looks a lot more like a real Bold font.
For now, I don't think anything can be done regarding the OS behaviour. As for the font, I guess it'll only get better once a Bold variant is added, which currently has quite a few open issues requesting it already.

**Comment by aaronbell** [comment]
Thanks for the feedback! This is covered in other issues, such as #43. Closing as duplicate.
