### ISSUE TITLE
— and - look the same

### ISSUE THREAD

**Issue by shuaiyuancn** [microsoft/cascadia-code#168]
# Environment

```none
Cascadia Code version number: 1910.04
Application (with version) used to display text: Any, e.g., Jupyter notebook 1.0.0
OS platform and version: Windows 10
Screen resolution (i.e. 220dpi): 1920x1080

Any other software? No
```

# Steps to reproduce

— and - look the same

![image](https://user-images.githubusercontent.com/1099375/67777431-a04dd700-fa59-11e9-98e4-cec523c1262d.png)

# Expected behavior

They shouldn't look the same.

# Actual behavior

They look the same.

**Comment by dwtaber** [comment]
En dash is also identical to these two.

**Comment by mdtauk** [comment]
Ordinarily the en dash would match the width of the letter n, and em dash, the letter m

But because this is a monospaced font, the letters are both the same width, as would be the hyphen and minus glyphs.

Perhaps the sizes should be adjusted so hyphen is shortest, followed by the en and em to maintain that relationship between the three glyphs.

The minus would match the plus, equals, divide horizontal stroke width

**Comment by dwtaber** [comment]
Consolas, Courier New, and Lucida Console all opt to maintain the hyphen < en < em relationship rather than the en = N, em = M relationship, and I think it's the way to go for this font as well.
