### ISSUE TITLE
Add № (Numero) symbol

### ISSUE THREAD

**Issue by andreich1980** [microsoft/cascadia-code#239]
# Description of the new feature/enhancement (with images if possible)
Please consider adding the **№** symbol [Numero Sign](https://en.wikipedia.org/wiki/Numero_sign). 
Right now it looks a bit off

![изображение](https://user-images.githubusercontent.com/17148882/74726718-00f36080-5251-11ea-984f-3d5b6b0c3858.png)

**Comment by DHowett-MSFT** [comment]
I do not understand. You have requested that we add it, but as far as I can tell it's already been added?

![image](https://user-images.githubusercontent.com/14316954/74768909-4bb7ad00-523e-11ea-8d8b-63bb2a768bcf.png)

**Comment by andreich1980** [comment]
I saw the symbol. I thought the N part should be a little bigger.

**Comment by uRohan** [comment]
I don't know if it's by design, but the [numero sign](https://en.wikipedia.org/wiki/Numero_sign#Technical_considerations) seems small. "N" is smaller than a quotation mark.
Example:
![Screenshot_20220908_101226](https://user-images.githubusercontent.com/11392016/189058629-4768d9fb-bf7e-4565-aa0c-60ee73540748.png)
![Screenshot_20220908_101113](https://user-images.githubusercontent.com/11392016/189058755-0db613aa-4fb7-4b0a-bd2a-89f8410fd147.png)
