### ISSUE TITLE
Cascadia code seems blurry

### ISSUE THREAD

**Issue by mimi89999** [microsoft/cascadia-code#249]
# Environment

```
Cascadia Code version number: v1911.21
Application (with version) used to display text: MS Terminal, GNOME Terminal, LibreOffice Writer
OS platform and version: Windows 10.0.19603.1000, Linux debian 5.5.0-1-amd64 #1 SMP Debian 5.5.13-2 (2020-03-30) x86_64 GNU/Linux
Screen resolution (i.e. 220dpi): 96dpi
```

# Steps to reproduce

Enter some text

# Expected behavior

Tex should not look blurry

# Actual behavior

Text looks blurry.

At first I thought that it's a MS Terminal issue https://github.com/microsoft/terminal/issues/5376, but then I tested in GNOME Terminal and compared several fonts in LibreOffice Writer on GNU/Linux and found the text to also be blurry. Please see the linked issue, especially:

![Screenshot_win10_2020-04-16_13:23:03](https://user-images.githubusercontent.com/8530546/79451630-1eda0900-7fe7-11ea-9979-ba0305fc5f69.png)
![Screenshot_win10_2020-04-16_13:27:24](https://user-images.githubusercontent.com/8530546/79451633-1f729f80-7fe7-11ea-9cea-5b130c40f49d.png)

![Capture d’écran du 2020-04-16 16-02-32](https://user-images.githubusercontent.com/8530546/79484301-b81f1480-8013-11ea-9a3b-a4889bbe5dd4.png)

![Capture d’écran du 2020-04-16 19-18-39](https://user-images.githubusercontent.com/8530546/79486539-21eced80-8017-11ea-8e92-51a645cf9bd8.png)

**Comment by DHowett-MSFT** [comment]
> Screen resolution (i.e. 220dpi): 1280x800

what DPI/screen scaling factor are you using.

**Comment by mimi89999** [comment]
```
michel@debian:~$ xrdb -query | grep dpi
Xft.dpi:	96
michel@debian:~$ xrandr | grep -w connected
LVDS-1 connected primary 1280x800+0+0 (normal left inverted right x axis y axis) 286mm x 179mm
michel@debian:~$ xdpyinfo | grep dots
  resolution:    96x96 dots per inch
```
Seems quite low.

**Comment by mimi89999** [comment]
But my resolution / screen size gives 113dpi.

**Comment by aaronbell** [comment]
'Blurriness' is a rather hard quality to quantify in text rendering as everyone's perception of what is blurry (or not) is different. I'm not sure what you're comparing to, but what you've shown in your samples appears to be the fonts rendering as expected given your screen DPI, especially since you're observing the same characteristic across multiple fonts and multiple OS environments. 

A bit of background—when a font is used on screen, the infinite resolution vector outlines of each glyph need to be adapted to the limited resolution environment of a pixel grid. As you can imagine, this can lead to significant degradation of the glyph outline quality.

<img width="462" alt="Screen Shot 2020-04-20 at 9 11 24 AM" src="https://user-images.githubusercontent.com/8460297/79773928-ec7e2380-82e6-11ea-8bee-97be1a38481e.png">
(from Beat's excellent [Raster Tragedy](http://rastertragedy.com/). If you ever wanted to learn way too much about text rendering.)

Historically, there were all sorts of (expensive) mechanisms to get around this problem, but this problem has been much reduced due to the prevalence of high-resolution screens. As such, many font rasterizers have moved to implementing 'font smoothing', which applies antialiasing to glyph outlines and allows curves to more perfectly replicate the actual vector outlines. 

The downside is that on low resolution screens, the result can start to look blurry, especially for folks who are used to seeing the sharp aliased outlines. 

In the old days of Windows (I think up to Windows 7), there was software called the [ClearType Tuner](https://www.howtogeek.com/howto/28790/tweak-cleartype-in-windows-7/) which allowed users to customize how text rendering worked in Windows, and customize it for their individual preferences. It *appears* to [still be available in Windows 10](https://www.tenforums.com/tutorials/80598-turn-off-cleartype-windows-10-a.html), but I seem to recall it not actually doing that much anymore, so your mileage may vary.

**Comment by mimi89999** [comment]
> especially since you're observing the same characteristic across multiple fonts and multiple OS environments.

I have this problem on multiple OS, but only with _Cascadia Code_. _Bitstream Vera Sans Mono_ that I'm using as my terminal font seems very sharp and _Fira_ fonts seem average. I obviously can't show the issue on my screenshots, but if you open them on a 96dpi screen you might notice the same thing that I did.

**Comment by mimi89999** [comment]
Besides the `@` that is too small and hardly readable, vertical lines (Serifs?) on top of `I`, `l`, etc. instead of being fin and black like in _Bitstream Vera Sans Mono_ are thicker and grayish.

**Comment by aaronbell** [comment]
Per my write up above, Cascadia Code has a bit for y-direction font smoothing set. This enables better rendering of diagonals and curves at high resolutions. It may be the other fonts do not. And environments that respect that bit will render the outlines more antialiased. 

As for the other issues, there's already an open issue on the @ sign that I'm planning to resolve, and in the case of the /I and /l, well, that's partly due to the darker character of the font and partly due that the outlines are not locked to the pixel grid, so the serifs may appear thicker and grayer (again, due to the lower resolution display).

**Comment by mimi89999** [comment]
OK. I understand.
Is _Cascadia Code_ targeting HDPI screens or will something be done to make it better on 96dpi? If not, then probably _MS Terminal_ shouldn't set it as default on low DPI screens because I'm probably not the only one to whom this font appears blurry on that particular screen.

**Comment by aaronbell** [comment]
The font was created to target contemporary hinting / rendering approaches, but there may be a way to improve it for 96DPI screens without too much work. Let me investigate and get back to you :).

**Comment by PhMajerus** [comment]
The ClearType Tuner is now included in Windows 10: %SystemRoot%\System32\cttune.exe

Note it doesn’t just let you set your sharpness and boldness preferences, ClearType uses the RGB subpixels of LCD displays to effectively triple the horizontal resolution to improve character spacing, vertical bars width and italic slants.
Running the CTTuner makes sure that Windows known your physical subpixels orientation to do that properly.

**Comment by Carighan** [comment]
In a way I'm relieved, I thought it was my eyes playing tricks on me. I come from using Consolas, and I was *sure* Cascadia Code seemed, well, blurry.

After reading this I swapped back and forth a lot, and yes, Consolas (and also codes such as Fira Code or Jetbrains Mono) are noticably "crisper".

I took some screenshots:

![jetbrains_mono](https://user-images.githubusercontent.com/33469/79966457-c0e96d80-848d-11ea-9d27-5bd2bef0b4a9.png)
![consolas](https://user-images.githubusercontent.com/33469/79966461-c1820400-848d-11ea-9c09-8e8a6ea56c4a.png)
![cascadia_code](https://user-images.githubusercontent.com/33469/79966462-c1820400-848d-11ea-9e09-b8bf654858af.png)

Compare elements such as the `i` in Consolas vs Cascadia Code, or the pink `t` in Jetbrains Mono. While Jetbrains and Consolas each have various "blurry" elements to their individual letters, only Cascadia is consistent in wanting to render each letter with a lot of grey/hinting every time. I think this is what makes it feel "blurry", because this overly greyscale-hinted antialiased state is the default, while with the other fonts the `r` in Consolas or the dot of the `i` in Jetbrains are an exception (and in zoomed look ugly, at that).

Is this more of a general problem how the font is meant to be used only on high-DPI displays maybe, and expects the display to have pixels way too small for me to notice this effect? If so, could future versions look into improving legibility at full HD resolutions?

**Comment by dasco597** [comment]
I was finding Cascadia code to be pretty crisp in windows terminal up until around a week ago when it turned into a fuzzy nightmare. I'm not certain if it was because of an update or maybe it triggered because I had accidentally zoomed out and back in again with control + scroll

**Comment by moths** [comment]
> In a way I'm relieved, I thought it was my eyes playing tricks on me. I come from using Consolas, and I was _sure_ Cascadia Code seemed, well, blurry.
> 
> After reading this I swapped back and forth a lot, and yes, Consolas (and also codes such as Fira Code or Jetbrains Mono) are noticably "crisper".

For me it looks like Cascadia is more Bold than the regular Consolas. Something between Bold and Regular Consolas. My tests below. Cascadia at top (with zoom 400%) at 11 pt and windows scaling at 125%. Consolas also at 11 pt, notice that all lines are 2 pixel wide compared to Cascadias 3 pixel wide lines, this make the font look 50% more bold. I like the Cascadia font, but it needs a real Regular (non bold) option.

![fonts](https://user-images.githubusercontent.com/3830930/80357409-4056b280-887b-11ea-86cc-95eca8313454.png)

**Comment by madig** [comment]
It's a matter of getting used to it. Cascadia is a thicker design than Consolas and that's fine. I use Cascadia Code everywhere and Consolas feels anemic to me now. I also prefer Cascadia's softer look. :shrug:

**Comment by aaronbell** [comment]
So. Some bad news. 

As Cascadia Code is now a variable font, and will be moving forward, modifying the hinting to reduce blurriness has become significantly more work and as such is a lower priority compared to other project tasks. Hopefully the new lighter weights now available in the variable font will help improve your experience!

**Comment by Carighan** [comment]
I just saw the release, I'll have a look. Thanks for the heads-up! 👍

**Comment by brokenthorn** [comment]
> It's a matter of getting used to it. Cascadia is a thicker design than Consolas and that's fine. I use Cascadia Code everywhere and Consolas feels anemic to me now. I also prefer Cascadia's softer look. 🤷

I've struggled with this myself but until you get a high DPI 4K screen you won't understand why Cascadia what made for or why.
Because on high DPI screens, text looks smaller and crisper, aliasing at like 2x would create a very small blocky font, so Cascadia is designed to be thicker, more rounded, to use that available space on these displays to produce more curvy, more legible font, because on 4K you won't see the blurred (shaped, rounded) edges.
