### ISSUE TITLE
Investigate rendering differences of TTF and OTF on Windows

### ISSUE THREAD

**Issue by madig** [microsoft/cascadia-code#277]
# Environment

```none
Cascadia Code version number: 2005.15
Application (with version) used to display text: Firefox and Chrome
OS platform and version: Windows 10 1909
Screen resolution (i.e. 220dpi): 109dpi

Any other software? Haven't checked.
```

# Steps to reproduce

When comparing TTF and OTF on e.g. http://www.cyreal.org/Font-Testing-Page/, the OTF appears significantly thicker, at smaller sizes, e.g. the "w" looks clogged.

# Expected behavior

TTF and OTF should have roughly the same thickness.

# Actual behavior

OTF (right) is significantly thicker, at least in the two DirectWrite-using browsers I looked at.

![image](https://user-images.githubusercontent.com/380829/82423493-bbc31280-9a7b-11ea-8c08-c9ca47eab45f.png)

# Questions for the Windows team:

- Does the DirectWrite CFF renderer apply stem thickening? Is the amount applied controlled by the usual ClearType dials? Is it dependent on the standard stem weight values in a CFF's PrivateDict?
- Does the DirectWrite CFF renderer grid-fit on the horizontal axis?
- Is the same linear alpha blending and gamma correction applied to TTFs and CFFs in DirectWrite?

**Comment by J0F3** [comment]
I have noticed the same in VS Code. When using OFT an the default font size of "14" the "1" (one) and "i" is very difficult to distinguish:
![image](https://user-images.githubusercontent.com/12759579/82453955-833e2b80-9ab1-11ea-999b-295bea7eb720.png)

But interestingly this is not a problem on a high dpi screens like the Microsoft Surface Devices have it. So on for example on my Surface Pro the difference of  "1" and "i" is very clear (with the same font size).

**Comment by madig** [comment]
IIRC, Adobe had their hand in the Windows CFF code and they also contributed the current CFF renderer in FreeType. The guy who did it mentioned that Adobe's own renderer does stem darkening, so I suspect they also put it into the Windows CFF renderer. It only triggers at smaller text sizes, once some pixel threshold is crossed, no darkening is done. That would explain that there's no diff on HiDPI screens.

Your first picture with the fused i-dot seems like an unhappy accident...

**Comment by aaronbell** [comment]
In my experience, OTFs (regardless of PS hinting) always render heavier and blurrier on Windows than a properly hinted TTF with correct GASP tables. Not sure if that's due to the rendering mode applied, or if there's special thickening code. 🤷‍♂️ 

I'm also not surprised that at high DPI they render more or less the same as the impact of hinting is reduced (and at a certain point, hinting is turned off entirely), so the two are more likely rendering using similar approaches. 

In any case, for best results, I'd suggest using the TTF on Windows :). 

This is not really a bug with Cascadia Code, though, since it is DWrite-driven. I'll leave it to @DHowett to get in touch with the DWrite owner. Closing!

**Comment by madig** [comment]
@DHowett may I prod you again about this :D
