### ISSUE TITLE
Increase vertical size of font to match Consolas, perhaps as an additional font

### ISSUE THREAD

**Issue by WascawyWabbit** [microsoft/cascadia-code#295]
Increase the vertical size of the font to match Consolas, perhaps as an additional font option?  The horizontal size already matches

As a visually impaired user, i must increase the size of Cascadia in order to get the same level of readability as Consolas, but that means that i get less text on screen.

**Comment by WascawyWabbit** [comment]
This is odd:

- Powershell window (not Terminal): create 2 powershell windows, one with Cascadia Code and one with Consolas, same size; dir in both: the Cascadia font is smaller vertically and horizontally.  Result: Consolas is easier to read.

- Windows Terminal:  PowerShell | Set font = Consolas; lir  Change font to Cascadia Code:: Cascadia is smaller vertically, but wider horizontally.  Result: on balance, Cascadia Code is easier to read.

- VSCode: I must be doing something wrong, as the edited file (Terminal settings.json) looked the same when setting font family to Consolas vs 'Cascadia Code', but the title screen showed narrower text when using Cascadia Code.

I wasn't expecting this variability.

**Comment by aaronbell** [comment]
Thanks for the suggestion! We don't have plans at this time to modify Cascadia Code to align with Consolas, but I know that there is interest in producing a width axis, which would allow you to fit more characters on the line.

As for the the variability that you're observing between applications, well, that's a complicated situation. Different applications use different metrics and ways to render fonts. Windows Terminal is using the most modern technology for text rendering, which means that Cascadia Code appears larger, whereas Powershell is using an older approach, wherein Cascadia Code appears smaller. I wish I could say it was simple!

In any case, since we're not planning to adjust Cascadia at this time, I will close this issue. Cheers
