### ISSUE TITLE
Some Cascadia Code Light's glyphs (or their elements) look even lighter in bold style in Microsoft Word

### ISSUE THREAD

**Issue by AlexYash** [microsoft/cascadia-code#336]
# Environment

```none
Cascadia Code version number: 2007.015
Application (with version) used to display text: Microsoft Word for M365 (ver. 2007 build 13029.20292 MS Store
OS platform and version: Windows 10 Pro (ver 2004 build 19041.388)
Screen resolution (i.e. 220dpi): 120dpi (125%)

```

# Steps to reproduce

Compare these Cascadia Code Light glyphs in regular and bold styles: 

B ę G g I i Į į j P T Y y r m Z z Ž ž  

# Expected behavior

Bold version should be thicker

# Actual behavior

![Cascadia Code Light issue](https://user-images.githubusercontent.com/45464862/88907024-d32f3080-d260-11ea-945b-fba6b3d752ad.png)

P.S. Thank you for the light versions of the font. They are very useful especially for printing.

**Comment by AlexYash** [comment]
Yes, I also guessed that this might be Word's issue and checked it in LibreOffice Writer. Funny part - it works correctly there. But there were some other issues with document conversion so it's not a solution in my case 
Just for better understanding of my scenario. I'm creating verbs table which look like this:
![Cascadia Code Light Word issue](https://user-images.githubusercontent.com/45464862/88938976-a72aa400-d28e-11ea-834c-4f381e8648cb.png)
I had to use bold style because there is no difference between black and red color when I'm printing on my b&w laser printer (I have no idea why there is no difference in grayscale - all settings are fine), so my idea was to make those chars bold so it would be easier to differentiate them.
I've also tried to export it to PDF and print it via Adobe Acrobat Reader. It handled it better but it looks that Reader doesn't handle variable font correctly as printed text looks like it has been printed using regular Cascadia Code font. I'll try to experiment with it later.

**Comment by aaronbell** [comment]
Also interesting is that it works fine in Word on Mac. 🤷‍♂️ 

Using bolder type is totally fine—I'd just suggest manually switching to "Cascadia Code Regular" rather than using the bold button. You'll get a bolder weight, and it won't display this weird behavior :/

Yeah, PDF export appears not to work as well as it should :(. I think that's a long-standing issue. For your purposes, I'd suggest uninstalling the TTF Cascadia Code, and instead installing the static instance OTFs. Screen rendering won't be as crisp, but you'll get the right weights in PDF export.

**Comment by AlexYash** [comment]
Thanks for hints!👍

 Looks like Windows Terminal "overwrite" OFT fonts with bundled TTF. I'll try to play around with it tomorrow.

**Comment by AlexYash** [comment]
I've tried OTF fonts but got another interesting effect.
Steps to reproduce:
1. Uninstall Windows Terminal and all Cascadia Code TTF fonts.
2. Install all Cascadia Code OTFs.
3. Install WT.

Looks like the system prefers TTF fonts as it reports WT TTF versions in Fonts settings and OTF for PL variations.
As a result MS Word works with Cascadia font family correctly now. Even that bold font issue which I had reported has disappeared.
But... Acrobat Reader DC now doesn't recognize Cascadia Code fonts correctly now. I've tried different PDF export options in Word including font embedding but it looks like this: 
![Cascadia Code Light Adobe issue](https://user-images.githubusercontent.com/45464862/89182309-2c1f0180-d59e-11ea-90d5-a83fbc1e53e0.png)
)

UPD. It looks like Acrobat Reader DC has some strange font handling mechanism as after several attempts it renders Cascadia Code glyphs correctly but still there are some issues with combining diacritical marks. 
![Cascadia Code Light Adobe issue 2](https://user-images.githubusercontent.com/45464862/89183449-ed8a4680-d59f-11ea-8b7e-5b15bfe4e81a.png)

Also Reader doesn't reflect Cascadia Code fonts in Document properties - only default system fonts.
![Cascadia Code Light Adobe issue 3](https://user-images.githubusercontent.com/45464862/89183803-786b4100-d5a0-11ea-8f45-9f8dbd33baf9.png)

P.S. I guess we can close this issue as it seems that these are applications' issues but not the font's ones. I just want to try to remove WT and TTF versions completely and look what will happen with OTF versions only.

**Comment by aaronbell** [comment]
Thanks so much @AlexYash for all your investigations :). Here's some info for you:

1) Windows Terminal will always prefer its own TTF instances (Cascadia Code and Cascadia Mono) of the font over any that are installed by the user. This can be overcome by setting the "PL" versions of the above two fonts, which are functionally identical (except for the addition of the PL glyphs). This is a known issue.

2) The issue with the combining marks was due to the way that glyphs2ufo converts formats. It should be resolved with PR #333, whenever that is pulled in. 

3) Unfortunately, I don't really know what is going on with Adobe Reader. I'd assume it has something to do with not supporting variable fonts, but couldn't tell you for sure. I'll be interested to find out the results of your testing just the OTFs. 


Getting back to the bolding issue—I don't have a definite answer as to why it is happening. One theory is that the boldening mechanism is misinterpreting the outlines and considering one or the other as a counter rather than a stroke, therefore shrinking it instead of boldening it. However, as I don't observe this issue in other environments, I believe it is external to the font's functionality (as in, the font is working correctly and it is being misinterpreted by an external engine) and so will close this issue.

**Comment by aaronbell** [comment]
Something else I forgot to mention. Instead of using the bold button for Cascadia Code in Word, I'd strongly recommend just selecting a heavier weight (like Cascadia Code Regular or SemiBold, for the Light). That way you'll get the correctly weighted forms instead of however the application decided to bold the glyphs.

**Comment by AlexYash** [comment]
@aaronbell thank you very much for your support. I've followed your advice regarding heavier weight as soon as you had suggested and it works for sure. Everything else is JFYI in case it could be useful for you. :)
