### ISSUE TITLE
In powerline, local changes symbol does not display in Ubuntu bash WSL 2

### ISSUE THREAD

**Issue by jpoiron** [microsoft/cascadia-code#337]
# Environment

```none
Cascadia Code version number: 2007.01
Application (with version) used to display text: bash on WSL 2, Ubuntu 18.04.4
OS platform and version: Windows 10 Pro build 19041.388
Screen resolution (i.e. 220dpi): 2560x1440
```

# Steps to reproduce

I'm trying to follow the tutorial for [setting up powerline in Windows Terminal
](https://docs.microsoft.com/en-us/windows/terminal/tutorials/powerline-setup). These same steps produced the same result on my laptop too.

1. Download release [2007.01](https://github.com/microsoft/cascadia-code/releases/download/v2007.01/CascadiaCode-2007.01.zip)
2. Extract, then install `CascadiaCodePL.ttf`
3. Open Ubuntu app, right-click title bar, choose Properties and change font to `Cascadia Code PL`
4. In bash, go to folder containing git project with a local change.

![2020-08-04_15-20-20](https://user-images.githubusercontent.com/3971132/89341049-54723300-d666-11ea-9565-aff89382ffee.png)

# Expected behavior

Beside the count of files changed, a symbol should be displayed instead of a box.

# Actual behavior

A box is being displayed instead of a symbol.

![2020-08-04_14-58-59](https://user-images.githubusercontent.com/3971132/89341600-293c1380-d667-11ea-844d-39538939f3b2.png)

**Comment by DHowett** [comment]
What glyph is that supposed to be? Do you happen to know its codepoint?

**Comment by jpoiron** [comment]
Wow, thanks for the fast response! Great question. I can copy that character out of there and paste it here... it appears to be a pencil: ✎

**Comment by DHowett** [comment]
Excellent! So, right now, the font doesn't contain a pencil glyph. That's alright, though, because it doesn't _really_ need to, because a font renderer can pick a good font that _does_ have a pencil if the font you're using doesn't.

I noticed in your screenshot that you're using the traditional windows console, not the new Terminal. The old console doesn't support font fallback, and it'll be some time before it does.

If you look at your powerline prompt in _Windows Terminal_, does the pencil show up?

**Comment by jpoiron** [comment]
Aha! Windows Terminal works like a charm. All I had to do was add `"fontFace": "Cascadia Code PL"` under the Ubuntu profile (or the default section I suppose).

Thanks for your help 😃
