### ISSUE TITLE
In 4K monitor, Android Studio bracket symbol display error.

### ISSUE THREAD

**Issue by Richyeoh** [microsoft/cascadia-code#338]
Configuration
![config](https://user-images.githubusercontent.com/56948566/89483868-b00c0000-d7cf-11ea-9baa-fcf146fb0f12.png)

Details display error
![error](https://user-images.githubusercontent.com/56948566/89483880-b8643b00-d7cf-11ea-9055-d5d5f553984f.png)

**Comment by Richyeoh** [comment]
This problem has existed a long time ago. At first I thought that reinstalling the Cascadia code would be enough, but it didn't solve it.

**Comment by Richyeoh** [comment]
## Smart completion will also show exceptions

![error](https://user-images.githubusercontent.com/56948566/89484353-e9913b00-d7d0-11ea-9cc0-92423eab1113.png)

**Comment by aaronbell** [comment]
Given that the font is showing the brackets correctly in the configuration page, it surprises me that they would not display correctly in other parts of the same application, and makes me suspect that there is something outside of the font that is causing the issue. 

Do you see the brackets when another font is used? Is there any sort of replacement that Android Studio does on those glyphs? 

With regard to your "Smart Completion", I'm not sure what I'm looking at. Can you clarify?

**Comment by Richyeoh** [comment]
Other font displayer normal, only Cascadia code display error,about "Smart Completion " I mean “Smart Completion” font also display error.

**Comment by aaronbell** [comment]
I've tested in Android Studio on both Mac and Windows on high resolution screens and have not been able to repro the issues that you're observing. 

<img width="687" alt="Screen Shot 2020-08-09 at 9 15 39 AM" src="https://user-images.githubusercontent.com/8460297/89736889-af6aa800-da21-11ea-80dd-20571b746d15.png">

Given that the font is displaying properly in the font settings in your screenshots as well as mine, it is my belief that the font is functioning properly and that the brace glyph is properly functioning. I'd guess that there is something external to the font that is causing the issue. 

I would suggest re-installing Android Studio. If you're not interested to do that, you might consider downloading and trying the PL versions from the [latest release](https://github.com/microsoft/cascadia-code/releases/tag/v2007.01), or perhaps try the OTF static fonts instead of the TTF. 

As this does not appear to be an issue with the font itself, I am closing this issue, but if you are able to provide a repro case please let me know!
