### ISSUE TITLE
Feature Request: Improvement - Semicolon

### ISSUE THREAD

**Issue by drbap** [microsoft/cascadia-code#346]
First of all, congratulations on the excellent work on the **Cascadia** fonts.

I am writing to suggest an improvement to the **semicolon** that could improve its legibility (*in my opinion*). Please see the attached image with 2 suggested semicolons.
![cascadia_cd_semicolon](https://user-images.githubusercontent.com/70039037/90965675-b7562d80-e4a0-11ea-9c87-da901269b09f.png)

Thanks for considering.

**Comment by aaronbell** [comment]
Thanks for the feedback! One of my goals with Cascadia was to ensure that it will render fairly clearly even at smaller sizes on low resolution screens. To that end, with the semicolon I wanted to keep the bottom portion as vertical as possible. Otherwise, at smaller sizes, an angled stroke doesn't totally fill a single pixel, so the stroke turns gray rather than being solid black. So instead of angling it more, I increased the length of the bottom portion in order to create better differentiation. 

Given the above goal, I am pretty happy with the current design of the semicolon, and don't intend to change it. Hope that helps clarify my intent!

**Comment by drbap** [comment]
Thank you very much for the reply and explaining the reasons why you designed the semicolon this way. It was just a suggestion. I still think the semicolon and comma could be improved (a bit more angled), but maybe it is a matter of taste. Anyway, congrats again on the great work.
