### ISSUE TITLE
Equals and other horizontal characters uneven rendering on Windows 10 / VS Code

### ISSUE THREAD

**Issue by charconstpointer** [microsoft/cascadia-code#377]
# Environment

```none
Cascadia Code version number: 2009.021
Application (with version) used to display text: Visual Studio Code 1.49.3
OS platform and version: Windows_NT x64 10.0.19041
Screen resolution (i.e. 220dpi): 3440x1440p @ 34' 100% scaling, but changing scaling does not help much 
```
Any other software?
```
Windows Terminal
IntelliJ
```

# Steps to reproduce

just type
```
=
```
or
```
===
```

# Expected behavior

I expected both lines to be the same width/height depends how you look at it also happens with other characters/ligatures; I can provide more examples if needed

The example below might look funny because its so enhanced but it is really noticeable when looking at text with normal zoom levels

# Actual behavior
3440x1440 34' screen
![](https://i.imgur.com/i5a9G7j.png)
2560x1440 27' screen
![](https://i.imgur.com/bVAEyu0.png)
and in comparison to Jetbrains Mono
![](https://i.imgur.com/23vBnXi.png)

**Comment by aaronbell** [comment]
Thanks for the feedback. 

Font rendering is a notoriously challenging area because it will differ quite significantly depending on the OS you use, the resolution of the screen, and the rendering approach used by a given application. Not to mention that different coding applications have different modifications that they do to glyphs, which changes rendering. Phew!

In TTF fonts, we add what is called "hinting", which is code built into the font that tells the rasterizer how to render the font. However, it is challenging to fully control glyph rendering since it depends entirely on how the glyph falls on the pixel grid (plus everything I mentioned above).

The approach used for this font was to try and 'lock' one part of a given glyph to the pixel grid (thus achieving high contrast / differentiation between white and black). And then other elements in the glyph are determined from there. But as I said earlier, things will vary depending on the rasterization mode, etc. In the case of the `===` above, there are only so many pixels available, so would you rather the glyph be not centered (adding a space between the bottom two lines), or fully merged (no spaces between any lines)?

In thinking about it, I do think I could try to make the `=` appear a bit more similar for your use case, but doing so could cause problems in other use cases. So there's a fine line to walk. 

In the case of jetbrains—I can't speak to the way that they have hinted the font, nor if the `=` appears as dark as the letterforms (I suspect it appears lighter), but their approach does not prioritize contrast. You get better consistency, at the cost of a more 'gray' rendering.

**Comment by jozsefk9** [comment]
Don't compromise contrast
