### ISSUE TITLE
Parentheses are asymmetric

### ISSUE THREAD

**Issue by rickdgray** [microsoft/cascadia-code#384]
# Description of the new feature/enhancement (with images if possible)
The parentheses are not symmetric across the x axis. I know this is trivial but, I'm sorry in my opinion it is very unpleasant and distracting to see. When paired next to each other as shown here, all I see is an incomplete heart shape.
![image](https://user-images.githubusercontent.com/3464912/96636416-e511f400-12e2-11eb-8cbb-9199bc0abb84.png)

Here's a screenshot of Fira Code's symmetric parentheses:
![image](https://user-images.githubusercontent.com/3464912/96636494-fa871e00-12e2-11eb-98c9-df013ec625b7.png)
Ahh, much cleaner!

I think a font primarily designed for coding should really nail these common cases and this is a pretty painful one to see.

**Comment by DHowett** [comment]
It would be helpful for you to include some or all of the info from the bug template (since you're reporting a bug, not a feature request).


```none
Cascadia Code version number:
Application (with version) used to display text:
OS platform and version:
Screen resolution (i.e. 220dpi): 

Any other software?
```

I ask solely because...
![image](https://user-images.githubusercontent.com/189190/96639872-2dc3b000-12d7-11eb-822f-0b8a9322b935.png)

![image](https://user-images.githubusercontent.com/189190/96639886-31573700-12d7-11eb-917e-c545b8bdb2d9.png)

...it would be very good to know what software has decided to render these parentheses incorrectly, and at what point size.

**Comment by rickdgray** [comment]
Interesting, I didn't expect this to be a bug. Makes sense, though. 

I'm using:

Cascadia Code PL version 2009.22
Visual Studio Pro 2019 version 16.7.6
Windows 10 Enterprise version 2004 build 19041.508
Screen Resolution is 1920x1080
The Scaling setting is set to 100%
In visual studio the point size is 10
In visual studio the zoom is set to 100%

I tried the same font and point size in notepad++ and don't have the same issue; it looks correct.

**Comment by aaronbell** [comment]
Cascadia Code has special code built in to help it render more clearly under certain conditions. Unfortunately, different applications (especially coding environments) do *all sorts* of fun things that can lead to inconsistencies in the rendering even with the special code. 

In any case, I'll take a look and see if I can improve what the hinting is doing for those particular glyphs.
