### ISSUE TITLE
Size makes font look different

### ISSUE THREAD

**Issue by troncomputers** [microsoft/cascadia-code#399]
# Environment

```none
Cascadia Code version number: latest
Application (with version) used to display text: SQL Management Studio 18.8
OS platform and version: Windows 10 20H2
Screen resolution (i.e. 220dpi): 1080p

Any other software?
Visual Studio 2019 and Visual Studio 2017 have same behavior.
```

# Steps to reproduce

Set SMO font to Cascadia Code SemiBold. Leave size at 10 and the font is thin and looks a bit like Consolas. Now change font size to 11.

# Expected behavior

It should looks the same no matter the size.

# Actual behavior

**font size = 10**
![font_10](https://user-images.githubusercontent.com/29543667/104431175-e3756680-5587-11eb-8dc3-b31758aa535b.png)

**font size = 11**
![font_11](https://user-images.githubusercontent.com/29543667/104431209-ec663800-5587-11eb-83a7-326a74f8cbb7.png)

**Comment by aaronbell** [comment]
Thanks for the feedback! You're running into what is called a 'breakpoint' in the font's rendering where the letter becomes large enough where a vertical stem appears to switch from two pixels to three pixels. As a result, the letters suddenly look a lot bolder than they once did. 

Unfortunately there isn't any way to solve this as the font is optimizing for whole pixels. I'd suggest using a lighter weight if you prefer the lighter look at a larger size.

**Comment by yg8ijvjvjv** [comment]
This is an invalid issue. This is the expected result of hinting. This font uses partial hinting because ttfautohint does partial hinting (hinting only vertically), so the horizontal stems are hinted to one pixel, then on the next size to two pixels. And in a font with full hinting and a renderer that supports full hinting, there would also be the switch from bilevel rendering to anti-aliased rendering (bilevel rendering is usually set on sizes hinted to single pixel stems).
