### ISSUE TITLE
`locl` features that swap 2 glyphs for 1 glyph

### ISSUE THREAD

**Issue by aaronbell** [microsoft/cascadia-code#412]
Opening a bug here for me to remember.

In the Dutch `locl` feature, there are substitutions to access ijacute forms:
```
sub iacute j by iacute_j.loclNLD;
sub Iacute J by Iacute_J.loclNLD;
``` 
Generally it is not ideal to substitute two user-entered glyphs for a single glyph in a monospace coding environment. A better implementation here is: `sub iacute j' by jacute`. This will mean removal of the `loclNLD` glyph mentioned above, and addition of `jacute`. 

In Catalan there are substitutions to access the `Ŀ` and `ŀ`:
```
sub  l' periodcentered' l by ldot;
sub  L' periodcentered' L by Ldot;
```
While this is a standard way to access the `Ŀ` and `ŀ`, I think that in this case it would make more sense to remove these substitutions and just leave the glyphs to look like `l·l`. These are atomic characters which can be accessed directly.

**Comment by ednl** [comment]
Am I correct in understanding that íj' (three glyphs) will now be substituted by íj́ (two glyphs)? And is this in any locality or just Dutch? Because Dutch does not have a jaccent. It does have an ij-digraph (ligature) where the accent, if needed, goes only onto the i, not the j. So the previous rule seems correct, except for the consideration that it is "not ideal" to replace two glyphs by one in a monospaced environment. This also seems true and would probably be unexpected behaviour for 99.9% of Dutch people who, after 30 years of MS Word, are now used to having a separate i and j in their ij. But it would still be more understandable than replacing j' with j́ which does not exist in Dutch.
