### ISSUE TITLE
Documentation: Update IntelliJ IDEA Setup Instructions

### ISSUE THREAD

**Issue by zekroTJA** [microsoft/cascadia-code#416]
For some reason, IntelliJ IDEA *(v2020.3.2)* does not recognize the fonts directory on Windows (10), so Cascadia Code will not show up by default in the font selection after default font installation.

A workaround which worked for me is to put the TFT-Files into the fonts directory of the IntelliJ IDEA installation, which is defaultly at the following path:
```
C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2\jbr\lib\fonts
```

It would be really nice if this would be added to the [Installation Instructions for IntelliJ](https://github.com/microsoft/cascadia-code/wiki/Installing-Cascadia-Code#setting-cascadia-code-in-intellij-ide-2019) in the Wiki Page.

**Comment by aaronbell** [comment]
Thanks for the feedback! This appears to be an issue with how JetBrains IntelliJ IDEA registers what is a 'valid' font and is due to the metadata changes we made to Cascadia Code with the most recent release. While installing the font into the fonts directory of IntelliJ IDEA is a viable work around, it is on JetBrains to make sure their system is working correctly. 

I have filed a bug with them [here](https://youtrack.jetbrains.com/issue/IDEA-262437).

**Comment by zekroTJA** [comment]
Ah okay, that explains why it worked perfectly with my older installation of IntelliJ with an older version of Cascadia Code.
Tank you! :)

**Comment by aaronbell** [comment]
To give an update, it turns out that one of the name tables I updated is not compatible with the mechanism that JetBrains uses to load fonts into their software. After reviewing the situation, I decided to roll back the change as that'll let you (and anyone else!) be able to use the font faster. However, I've suggested to JetBrains that they need to fix their code :).

I'll push a fix in the next release.
