### ISSUE TITLE
Option to use the old italic version

### ISSUE THREAD

**Issue by n-gao** [microsoft/cascadia-code#468]
# Environment

```none
Cascadia Code version number: 2105.24
Application (with version) used to display text: vs code
OS platform and version: Windows 10 20H2
Screen resolution (i.e. 220dpi): 96dpi

Any other software?
```

# Steps to reproduce
The new italic font is hard to read
![image](https://user-images.githubusercontent.com/9084670/119635101-a497cd00-be13-11eb-8dd5-75392c9c2c67.png)

# Expected behavior
I would like to be able to use the old italic font.

# Actual behavior

**Comment by Dimension4** [comment]
This is how my call stacks in log files in vs code look now
![0362](https://user-images.githubusercontent.com/11558535/119640323-c9427380-be18-11eb-8718-efcec91bb131.png)

**Comment by DennisGaida** [comment]
Also chiming in - the new italic styles sure are opinionated. Besides the release notes I can't find any reasoning why they look the way they look. Personally I think the characters look out of place (e.g. the lower-case L or the lower-case R) and don't fit well together. The examples provided above show the problems.

Beside that I think some of the letters are beautiful (e.g. the lower-case L), they just really don't fit well with the rest and I would love to just have an italic version of Cascadia Code. Maybe Aaron Bell can chime in and explain the reasoning for the italic version?

**Comment by Pecnut** [comment]
I like the new italics a lot in general, and it's really nice to have them finally! Thank you @aaronbell! But I would like to suggest that the lowercase 'r' really doesn't look like an 'r' at all if you didn't grow up in a country which teaches that sort of handwriting. With my single data point, cursive handwriting in the UK doesn't use this shape at all (see for example, https://i.pinimg.com/originals/63/9e/48/639e48a44e09f2fe8c86abb17e25ed08.jpg), so I find it  quite hard to read.

You may totally choose to ignore this comment but I thought you might like to know. I have no idea if a stylistic set might be a solution for this one character, should you be interested in doing so. But no pressure; just for your information. Thanks! :-)

**Comment by pstranak-sw** [comment]
People in different countries write (draw) letters differently. For example, the new "x" looks like my handwritten "z". I would expect a coding font like Cascadia Code to be universal, if possible.

Right now, half of the letters look like handwritten letters in my country, but the other half look like printed letters. When I see such text, the first impression I get is a broken font where half of the letters failed to render properly. It takes some time to get used to it.

While the previous version looked more mundane, it was consistent. But please, don't take this the wrong way. I like the idea of making the italics prettier, it just needs more work.

**Comment by Uxorious** [comment]
Isn't an Italics version of the font supposed to be the same font as the normal/bold one.
As it is right now, Italics looks like a completely different (handwritten, non-connected and super hard to read) typeface!
I really miss the old Italics now :-(

**Comment by mdtauk** [comment]
There was no previous italic version, what you saw was apps faking it by slanting the upright letters.

Perhaps this ask should be an optional Oblique version which could be used (not sure how you would specify italics to use the alternate font?

Maybe the newly added Italic could have a cursive stylistic set, and more traditional italicised glyphs where there are currently loops or a-typical letter shapes. - The lowercase **r** for instance feels unusual to me, and I am from the UK.

**Comment by MOYUtianming** [comment]
Hey,it is beautiful for Web or UI , but it is terrible to code , 

![image](https://user-images.githubusercontent.com/47681299/119779524-5bbb4380-befb-11eb-9bc7-91678b409582.png)

I hope you can divide Code font(just for code) and general font(for general use) , for me , I have no objection to using them when I am reading e-books  , but when I am coding , I just want a font that can make me read more quickly and clearly.

**Comment by TheDecryptor** [comment]
> Isn't an Italics version of the font supposed to be the same font as the normal/bold one.
> As it is right now, Italics looks like a completely different (handwritten, non-connected and super hard to read) typeface!
> I really miss the old Italics now :-(

Italic is supposed to be a cursive variant, while Oblique is a slanted version of the normal upright variant

**Comment by C1710** [comment]
> 
> 
> People in different countries write (draw) letters differently. For example, the new "x" looks like my handwritten "z". I would expect a coding font like Cascadia Code to be universal, if possible.
> 
> Right now, half of the letters look like handwritten letters in my country, but the other half look like printed letters. When I see such text, the first impression I get is a broken font where half of the letters failed to render properly. It takes some time to get used to it.
> 
> While the previous version looked more mundane, it was consistent. But please, don't take this the wrong way. I like the idea of making the italics prettier, it just needs more work.

The new uppercase X actually looks like the lowercase Greek letter χ.  
While I coincidentally found that in the word LATEX (where it would be correct/appropriate to use Chi instead of X), it's usually rather strange...

**Comment by LarnuUK** [comment]
For note, the new ~~italics~~ cursive style doesn't appear to be too well received over on [Stack Overflow](https://meta.stackoverflow.com/questions/407977/the-italic-fonts-on-team-are-hard-to-read-in-non-capital-letters), whom changed their default monospaced font to Cascadia Code, for those who have it installed, quite [recently](https://meta.stackexchange.com/questions/364048/we-are-switching-to-system-fonts-on-may-10-2021).

**Comment by todonovan** [comment]
Adding another voice asking for an option for the old italics. This has been my favorite programming font, but this change has immediately made it unusable for coding for me. I'm not sure where the trend of cursive in programming fonts originated, but I find they totally defeat the purpose of programming fonts -- which are supposed to be immediately and clearly readable. Cursive is anything but that. Adding another font that is Cascadia Cursive and leaving the mainline font alone seems like a much more reasonable approach.

**Comment by benc-uk** [comment]
"Argh what has happened to all my comments!!? is my font cache corrupt?" my first thought

Seriously this is such a huge change to force onto everyone, there needs to be some way to opt into these cursive style italics, they look so incongruous to the rest of my code

**Comment by donn** [comment]
This is so jarring that I don't know where to start. What prompted this change. 

![image](https://user-images.githubusercontent.com/12652988/119917551-13d20600-bf67-11eb-96bb-9551f98a45c8.png)

**Comment by x9** [comment]
This is incredibly difficult to read and is, frankly, a confusing design choice for a code font.

Please reconsider.

**Comment by benc-uk** [comment]
The readability is so poor, this change seems to go in the face of the drive to have better accessibility and inclusivity

**Comment by mcendu** [comment]
I think this version of italic should be put behind an `ss**` option, as quite a few people here stated that it is too handwriting-esque and hard to read.
This is a playful font for sure, but playfulness shouldn't be taken to *that* extreme.

**Comment by rashil2000** [comment]
There are some very good monospace fonts out there which implement non-cursive italic variants, and they look beautiful while at the same time retaining readability. Some examples are:
- Consolas
- Recursive Mono
- Jetbrains Mono
- Clincher Code
- Dank Mono (don't judge by the name xD)

These can serve as inspiration if Cascadia folks ever want to make a non-cursive italic variant, and also as alternatives to Cascadia for the time being.

**Comment by pstranak-sw** [comment]
@DennisGaida I agree.

The "k" is still pretty similar to its printed version and more or less matches the printed design of the rest of the letters. I would not mind keeping it as it is.

But "r", "f", "s", "l" are clearly in a handwritten design and don't match their printed versions at all. They are nice, but they stand out in the text.
Interestingly, "a" is clearly handwritten, but somehow still easily recognizable. Maybe because even different people write the "a" the same way?

**Comment by LarnuUK** [comment]
Although I agree that the *k* is easily identifiable, @pstranak-sw , it is still quite dissimilar to the non-italics k. The italics one has a "loop" while the non-italics has 2 "flicks"; none of the other characters (apart from those highlighted) significantly change their design. 

For a monospace font that is designed to code in, and is the default and shipped font with Windows Terminal, then I think that consistency is really important, and characters should be similar regardless of if they are **bold**, *italics* or not. Otherwise it *could* be mistaken that the k and *k* are different characters.

**Comment by pstranak-sw** [comment]
@LarnuUK Yeah, that's why I mentioned also "a". If the letters are easily identifiable, it's good enough for me. And I don't care whether it is because everyone writes them the same way ("a") or that they look similar to their printed versions ("k").

**Comment by codeman38** [comment]
I don't mind the other italic characters, but the current shape of `r` is a deal-breaker for me - it's far too easily mistakable for an `n` especially at small sizes.

![image](https://user-images.githubusercontent.com/386563/120004502-d8562c80-bfa4-11eb-999e-9873674a7a2f.png)

**Comment by J3Rik0** [comment]
I'd like to share some of my programming font geek knowledge, after trying out on different OSes a considerable amount of programming fonts.
First off, stop mentioning Dank Mono, it's horrible with ClearType, it's been optimized for Mac and its tweaked grayscale rendering, it's horrible on Windows and Linux. It's a rip off if you ask me, too much money for such low effort, at least hint the font properly.

Cursive writing, not sure where you people learn to write cursive, or why you weren't taught to write it for that matter, the "r" and "x" look ok from a cursive writing perspective 
![image](https://user-images.githubusercontent.com/1242984/120045392-8f3fc000-c018-11eb-807d-7988ce90aa17.png)

I'm not sure where they teach to write the cursive r as this -> r instead of the one in the image above, just look for fonts designed 30+ years ago, if it's not meant to be cursive the r looks like r.

So, to also come with a possible solution, not just to reply to snarky rants with snarky rants, the build workflow of Cascadia is above my hobbyist know-how, but I did work a bit with FontForge and it has an automatic slanter where you take the regular variant, you give it the degrees to slant and presto, you get automatic italics with no effort made. If something like this can be done, we can have italics.

The problem with letting the OS slant the font is that the font gets slanted per application, some make it oblique which is waaaay too slanted, or moderate like it does on Mac. From my past experience, 8° slant angle is the sweet spot for most of the fonts I modified.

As an example, personally I'm in love with that loop k, variants can be built and shipped similar to how Fantasque Sans Mono does, it provide both a normal k and a looped k variant https://github.com/belluzj/fantasque-sans

So, to summarize, don't sh*t on the work the Cascadia Code team does, go for middle ground, ask if just slanted variants for italics are possible given the tools that they use because you're not a fan of cursive italics. Be polite and ask if there are possibilities, don't be an entitled brat and ask the team to change whatever you personally don't like. It's a product that needs to fit a large audience, not your own personal team working on your own personal requested stuff.

Personally, I'm good with the italics and how they look, and I can understand that this is not for everyone, asking the Cascadia Code team, can we automate a slanted version in the build that just angles the regular variant to a couple of degrees? And ship 2 italic variants? This is my suggestion to basically please everyone.

**Comment by cjj19970505** [comment]
People from non-English countries like me might find this kind of italics hard to read. We have read printed letters in English learning and never seen a hand-writing font like this before. There are cases I found myself often fall into:
1. The lower case "s" and "r" leads some words completely out of their printed "shapes".
2. "n" and "r" are too similar (in my opinion). I thought I read a "Cneat" when I use this italics for the first time.

**Comment by ifaswind** [comment]
💔 This italics just so hard to read in code...

**Comment by gorjiali** [comment]
nice italic version with style and readability by dank mono 👇, "r" character is very important in coding

![Capture](https://user-images.githubusercontent.com/49091958/120097931-50a92300-c148-11eb-865e-0e0feb73f614.PNG)

**Comment by hxhc** [comment]
The R and S are the most difficult to read for coding. I strongly hope there would be an option to use the old italic version.

**Comment by jadedarko** [comment]
If this does end up happening, please let us use the existing italics - even if that's a different font

The new italics are absolutely beautiful and I love the cursive r and s.
It makes reading comments so much nicer ☺️

**Comment by patrickfatrick** [comment]
Perhaps Aaron can consider style variants like what fantasque sans mono did for the "loopy" lowercase k (or recursive did for a bunch of letter variants). The specific letters people most have issue with could be offered as less stylized options in the font. 

I just want to clarify, I like this italic, it's a lot of fun and for me something fun is very important in a font I look at all day.

**Comment by ExE-Boss** [comment]
There is no real old italic version. That’s just the font renderer applying a skew transform to the text.

**Comment by mikewizc** [comment]
Actually I don't think this is just a few characters issue, these are totally two different fonts. Even the `font render applying a skew transform` is better than this one.

**Comment by mikewizc** [comment]
Actually I don't think this is just a few characters issue, these are totally two different fonts. Even the `font render applying a skew transform` is better than this one.

**Comment by jRimbault** [comment]
IMO, the italic version of a font shouldn't be a radical departure from the style of the normal font. Here we have 2 fonts with really different style and mood. I also agree the skew transform is better than this comic-y style.

**Comment by JonnieCache** [comment]
Does anyone even know how to uninstall this curved font? It seems like cascadia code is part of some kind of package, and is not present in the fonts directory. If I click on it in the windows 10 fonts UI, it crashes silently.

**Comment by LarnuUK** [comment]
> Does anyone even know how to uninstall this curved font? It seems like cascadia code is part of some kind of package, and is not present in the fonts directory. If I click on it in the windows 10 fonts UI, it crashes silently.

Using the fonts settings is what you want here.  Find the font by typing "Cascadia" into the Search bar, and then scroll down to Uninstall, under all the font faces, and click it. Then, if you want the old style with the Italics faces missing, download the [prior version](https://github.com/microsoft/cascadia-code/releases/tag/v2102.25) and install.

Alternatively, you could delete the font files (I suspect that'll work). If you installed them as a user install then they will be located in `C:\Users\{Your User}\AppData\Local\Microsoft\Windows\Fonts\`. If you did it as a system installed font it will likely be in `C:\Windows\Fonts\`.

**Comment by JonnieCache** [comment]
>Using the fonts settings is what you want here. Find the font by typing "Cascadia" into the Search bar, and then scroll down to Uninstall, under all the font faces, and click it. Then, if you want the old style with the Italics faces missing, download the prior version and install.

When I click on cacadia code in that UI, the window closes itself silently. I guess this is a windows 10 problem.

**Comment by LarnuUK** [comment]
> When I click on cacadia code in that UI, the window closes itself silently. I guess this is a windows 10 problem.
I was using Windows 10 when I wrote those instructions.

**Comment by DavidGamba** [comment]
@JonnieCache I am running into the same issue, it seems like they are bundled with the terminal:

![image](https://user-images.githubusercontent.com/1115287/120371964-d4dbe180-c2d3-11eb-84ad-da36e2633991.png)

Anybody knows how to safely uninstall those to install the previous release? Can you install fonts as aliases so we don't have to override the bundled one?

**Comment by rowanfreeman** [comment]
I fixed this in VS Code by changing my font family to `'Cascadia Code PL'` instead of `'Cascadia Code'`.

**Comment by antiz** [comment]
> I fixed this in VS Code by changing my font family to `'Cascadia Code PL'` instead of `'Cascadia Code'`.

Are you sure you are looking at Cascadia Code (and not the next font in line, like Consolas)?
See #467.

**Comment by nathan-alden-sr** [comment]
Oof. Talk about jarring... I, too, had thought this was some kind of rendering bug. The vast differences in appearance between not only the oblique and normal characters but also some cursive characters vs. other oblique ones is too much. I've been forced to revert back to Consolas in VS Code, VS, and Windows Terminal until this is corrected.

IMO, `Cascadia Code` should've remained untouched--oblique--while a new font was created that includes the cursive styles. Even then, the cursive styles are nigh unreadable, and several people from other areas of the world, on this thread and elsewhere, have valid complaints.

I'm old enough to have learned cursive in grade school here in the US and if I wrote like this font, I'd have received some very poor grades for sure.

**Comment by jessebarocio** [comment]
I don't doubt someone spent a lot of time on the design of the new italic characters. It does look good... I'm just not sure it belongs in a font that is primarily designed for reading and writing code.

**Comment by aaronbell** [comment]
First off, I want to say thank you to all of you who provided constructive feedback in your comments here. For everyone else, please remember that there is a human (me) who spent a lot of time creating this font. 

OK. 

In consultation with the other folks on the team, we have decided to make the following changes:

- the default form of the `s`, `f`, `r`, and `l` will be changed to 'less cursive' versions:
<img width="798" alt="Screen Shot 2021-06-03 at 2 35 13 PM" src="https://user-images.githubusercontent.com/8460297/120715060-ec080400-c478-11eb-8daa-ecd7b43409c2.png">


- the more cursive forms are still accessible, but now require the `salt` or `ss01` OpenType feature to be enabled in software. For reference on how to enable Opentype features in VS Code, please see [here](https://github.com/microsoft/vscode/issues/82153). Unfortunately, you will need to determine if your software of choice can support OpenType features. 

*** *** *** *** *** *** ***

Additionally, I would like to address a few misconceptions that have been brought up in this thread. 

`This is a major change to the existing Italic`
There was no italic previously. What was being displayed when an Italic was requested was a faux, mechanically-slanted version of the upright forms. What we have created is the true Cascadia Code Italic, and will continue to be so. No going back. 

`Italics must look the same as the upright—these are two different fonts`
When we think about 'adding emphasis' to text, there are two approaches—a "True Italic" that is derived from the tradition of scribal handwriting developed during the Renaissance, and an "oblique" which is (or should be) an optically-corrected, slanted version of the upright. 

Due to their origin in handwriting,"True Italics" often have different forms, such as the single-story `a` like in Cascadia Code Regular vs a double-story `a` in Cascadia Code Italic. Other examples are double vs single-story `g` (which Cascadia doesn't have), addition of entry strokes / exit strokes, and changing the stroke speed / skeleton shapes. This separation between the upright and italic is *extremely common*, and used in many, many fonts in the world, including coding fonts such as Operator Mono, Dank Mono, and Victor Mono.

Personally, I find that the "True Italic" forms help create more clear differentiation between comments and code than Oblique forms (not to mention are more FUN! Which is the whole point of Cascadia Code)—especially in situations where syntax highlighting is missing.

`The cursive forms are super different than the other letters`
Certain letters, yes, have more cursiveness than other letters, but that is true of Cascadia Code Regular as well. Some letters have serifs, others do not. Doesn't that bother you as well?

Also, the 'other letters' in Cascadia Code Italic are actually not obliques either, and all letters have been tweaked to give them a stronger 'true italic' character than a standard oblique. If you look carefully, most letters are actually quite different, such as `adbepqkvwxy` The letters that became cursive we felt were key to driving the character of the font that we wanted, not unlike other cursive coding fonts. Ah well. 

`Can't you just provide two versions of the font?`
It is difficult to do so. In order to ensure that when someone requests an 'Italic' they get the right font, there can only be one that is specifically linked to the Regular. So the OpenType route is the most reliable (and also prevents issues if someone installs both italic forms). Sadly, not all software may be able to support applying the `salt` or `ss01` features, so in that case, I apologize for the loss of cursive forms.

**Comment by Evotron** [comment]
True italic forms should be the default. If it’s called italic, it should be italic. If people want an oblique, they should request an oblique. Don’t make the italic less italic. I love it, and that’s what was requested: an italic!! Not an oblique. I don’t want to see obliques in an italic. If you want to make changes to the italic, make the capitals more italic because they look like obliques. The ‘O’ doesn’t have swirl, and the ‘E’ is straight up oblique.

Why should I have to activate an OpenType feature to access an italic ‘s’ when the typeface is an italic? I don’t understand why the default is going to be an oblique ‘s’. Shouldn’t an oblique Cascadia be created for that?

Putting oblique characters in an italic doesn’t make sense. Let the italic be an italic. Create an oblique if you want to have oblique letterforms. It’s bad design to miscategorize things and put them where they don’t belong. 

These changes seem reactionary and misguided. It seems like some people wanted an oblique. Great—request an oblique. But destroying the italic version is not right.

**Comment by aaronbell** [comment]
@Evotron The updated forms are not "obliques"—note that I never said I was swapping the forms for oblique forms. The `f` alone is an proof of that. The `r` follows the adjusted skeleton of the `n`, the `s` has been tweaked a bit, and the `l` follows the adjusted shape of the `i`. 

The shapes in the OT feature are an added 'cursiveness' which gives the italic a particular look and feel. However, the key argument, at least for me, is that this is a default font and it needs to be readily recognizable to people around the world. Not everyone has studied cursive, let alone US cursive, so that means it will be implicitly more challenging for them. By making this change, we are enabling a wider range of people to be able to read the font. That's it. 

As for why I don't just create a separate font, see my comment above (`Can't you just provide two versions of the font?`). If this was a solo project without dependencies on WT it would be fine. However, with that dependency, it is untenable.

**Comment by tylerszabo** [comment]
Unless it's a novelty font the primary feature should be readability over aesthetics; I'm pleased that Cascadia is going to opt for a readable and accessible form by default.

**Comment by aaronbell** [comment]
@tylerszabo I'm not sure I would necessarily call Operator Mono (and other such cursive coding fonts) a 'novelty font'. It has a particular look, and aesthetic that people love, even for coding. I'd argue that the cursive forms in Cascadia Code are at least on par with Operator in terms of legibility and clarity.

But one has to choose to 'opt in' to Operator. Folks are being defaulted into Cascadia. So despite our love for the cursive forms, they do not serve the world over.

**Comment by efaulhaber** [comment]
Great work! This looks very consistent in my eyes and I can't wait to use it in my editor.
When should we expect the next release?

**Comment by Evotron** [comment]
Readability ain’t a problem with the cursive forms. Maybe it’s because I live in Special District, Republic of Colombia and we use the Roman alphabet? It’s a shame I have to go out of my way to make an italic look the way it’s supposed to.

I’m shocked I even have to say that. At least, you’re not getting rid of the true italic letterforms. When I ask for a bacon cheeseburger, I hope the restaurant doesn’t give me two buns and some mayo, telling me it’s because some people had some problems with a bacon cheeseburger being a bacon cheeseburger.

**Comment by aaronbell** [comment]
@efaulhaber Not sure. Soon, I expect.

@Evotron Well, I'm glad that it worked perfectly for you as is! Sorry for the extra trouble.

**Comment by LarnuUK** [comment]
I would hope that the vast majority of users here do appreciate the work you and others out into the font many of us have come to enjoy using, @aaronbell , and I hope that the comments here haven't ruined or shattered that ideal for you all.

I think what surprised many was that this wasn't something we were expecting, not without a "heads up" at least; I am sure that many that use the font are subscribe the notifications here, and/or Microsoft blogs that tell us about stuff like Cascadia Code. I myself found out about it in an announcement blog several years ago when it came out and have used it in many environments since.

As the font now comes shipped with Windows Terminal, has been adopted by many in their IDEs, used on websites *including Stack Overflow* as their default mono spaced font the sudden change was, in some ways, bound to draw an influx of sudden feedback; especially when the font is automatically updated my the Windows Store and thus the changed happened "overnight" with no user input for some. 

If there are drives to do something like adding big changes to the font, I think the community would appreciate knowing before hand to give their opinions. Unless I, and many others, missed a blog post that said that this was coming, along with the "cursive" styles?

So yes, we are grateful for the work you all put in. There clearly many that greatly enjoy the font, as the fact so many have responded here shows quite how many use it in their daily lives.

**Comment by aaronbell** [comment]
Thank you @LarnuUK. I'll pass along the feedback.

**Comment by mdtauk** [comment]
> Thank you @LarnuUK. I'll pass along the feedback. 

Please don't be disheartened with the community @aaronbell with the way some have posted their feedback on here.

**Comment by pstranak-sw** [comment]
@aaronbell Thank you for looking for a middle ground. And also for not abandoning the idea of the Italics altogether. If my comments were among the harsh ones, I apologize for that.

As @LarnuUK wrote, the font has become too popular for any sudden changes. On one hand, that's a sign of a success, but on the other hand, there is a so much bigger risk of making someone upset.

BTW, personally, I'd remove the bottom serif from the new `r`, as it looks rather formal compared to the rest of the letters. But that's just nitpicking and feel free to ignore it.
![image](https://user-images.githubusercontent.com/37192399/120737009-9883cd80-c4ed-11eb-9ca4-3636ba8ce2de.png)

**Comment by pstranak-sw** [comment]
And I'll miss the original `l`. A slimmer version with a less dominant loop would make it more similar to a printed version, while keeping the more natural look. Maybe something like in the Dank Mono. But I can imagine that it would still not be recognizable enough for many people. So I understand its complete replacement.

**Comment by arilbernhard** [comment]
> Personally, I find that the "True Italic" forms help create more clear differentiation between comments and code than Oblique forms (not to mention are more FUN! Which is the whole point of Cascadia Code)

I think a lot of the confusion with this change comes from the misconception that the whole point of Cascadia Code was readability and usability, instead of fun.

**Comment by aaronbell** [comment]
@arilbernhard

Like I said before, the design is legible and it is readable even with the cursive elements—it wouldn’t have been approved by Windows Terminal if it wasn’t. Just because you don’t find it to your preference doesn’t make it a bad design or that we prioritized aesthetics over legibility.

**Comment by aaronbell** [comment]
@pstranak-sw yes, I’m sad to see the cursive forms go as well. Is actually encourage you to try them for a bit. Once accustomed to seeing them (versus more standard obliques) I think you’ll become quite comfortable with it.

Anyway, who knows, maybe I’ll tweak things a bit more ;)

**Comment by arilbernhard** [comment]
> @arilbernhard
> 
> Like I said before, the design is legible and it is readable even with the cursive elements—it wouldn’t have been approved by Windows Terminal if it wasn’t. Just because you don’t find it to your preference doesn’t make it a bad design or that we prioritized aesthetics over legibility.

As many have pointed out in this issue already, the font was quite literally illegible and unreadable for many - me included. The cursive in this font is completely different from the cursive I learned in school. I have never seen anything like it in my language.

**Comment by DHowett** [comment]
> 
> the whole point of Cascadia Code was readability and usability, instead of fun.
> 
> 

People have made broad statements like this during this thread, and I just want to set the record straight: we do not market the Cascadia family primarily on its readability, though of course a readable font is desirable.
The first adjective in the repository description actually _is_ "fun". Considering the design of the 3, the K, and the whimsy in the other letter forms this shouldn't come as a surprise exactly.

I see the difference between the `r` and `s` that some of you find illegible compared to more common forms similar to a two-story `a` or a `g` with a closed loop on the descender. Nobody would look at either of those and say (paraphrasing), "this font is garbage please delete it."

We're moving to more common letterforms because of community feedback, but there is an intangible _spirit_ to the Cascadia family that I think we should honor.

Anyway- that's only my 2c 😄

**Comment by Sherlock-Holo** [comment]
I met this problem too

**Comment by jozefizso** [comment]
I would preferer these new not readable italics would be in a new **Cascadia Italics** font set and the **Cascadia Mono** and **Cascadia Code** would use the old and readable characters.

**Comment by mdtauk** [comment]
I think there is scope to add flourish whilst maintaining legibility with those non US users who either learnt different forms of cursive (taught as joined up writing in the UK) or non English native speakers who have to use English words for coding scenarios.

![image](https://user-images.githubusercontent.com/7389110/120923080-7db78180-c6c4-11eb-9b59-fb9e7ba0876a.png)
_This is what in the UK would be considered the correct form taught to kids_

and this is an example of a quick sketch I did with the surface pen
![image](https://user-images.githubusercontent.com/7389110/120923863-a8a3d480-c6c8-11eb-8d5f-40370e1e7718.png)

**I am not saying these are the forms any cursive characters should take** only that there may be more readable forms you could consider as you explore in the future

**Comment by Jeddix** [comment]
@DHowett 

I think the big problem here is that your original goals don't align with Cascadia Code becoming the default font in Terminal and Visual Studio. A fun font would be fine in many use cases but I personally don't see "being the default font in an IDE" as one of them.

Don't get me wrong, I really appreciate the work that you are putting into this but I think that your goals are not what the users expect of the default font in Visual Studio.

**Comment by patrickfatrick** [comment]
@aaronbell You should consider making the original design the default and using the opentype features to "downgrade" it to the more buttoned-down variant :)

This is what [fantasque sans mono](https://github.com/belluzj/fantasque-sans) did for its more controversial lowercase-k glyph and I don't think many people are complaining about it now.

**Comment by bitigchi** [comment]
I really like the initial italics, and it will be sad to see them go. It should really be an option.

I was thought cursive using this style of lettering, and it really feels nostalgic and comfortable. Please keep it default, or as an option. I also think it adds character to the typeface in general.

**Comment by LuoZhongYao** [comment]
This is the most garbage programming font I have ever seen

**Comment by DHowett** [comment]
@LuoZhongYao if you can't figure out a nicer way to express your opinion, I invite you to _leave._

**Comment by lizy0329** [comment]
> I like the new italics a lot in general, and it's really nice to have them finally! Thank you @aaronbell! But I would like to suggest that the lowercase 'r' really doesn't look like an 'r' at all if you didn't grow up in a country which teaches that sort of handwriting. With my single data point, cursive handwriting in the UK doesn't use this shape at all (see for example, https://i.pinimg.com/originals/63/9e/48/639e48a44e09f2fe8c86abb17e25ed08.jpg), so I find it quite hard to read.
> 
> You may totally choose to ignore this comment but I thought you might like to know. I have no idea if a stylistic set might be a solution for this one character, should you be interested in doing so. But no pressure; just for your information. Thanks! :-)

This approach is like ant-design forcing add Christmas eggs.

**Comment by DHowett** [comment]
It is unlikely that you have a mew opinion to add to this thread. If you feel like you do, e-mail it to me. Locking for now :)
