### ISSUE TITLE
 Cascadia Code 2105.24 crash in Visual Studio 2019 and Sql Management Studio 18

### ISSUE THREAD

**Issue by spike1234** [microsoft/cascadia-code#483]
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows 10  [Version 10.0.19042.985]

### Other Software

Microsoft Visual Studio Enterprise 2019 Version 16.9.6
Sql Managemente Studio v18.9.1

### What happened?

When I set Cascadia Code as my font, they both crash to desktop.

**Comment by aarondglover** [comment]
I had an Issue with VS2019 (latest enterprise version) just yesterday,

My Code Windows appeared blank and I would get some wierd errors about Illegal Operation when opening new code files.

The issue turned out to be a corrupt cascadia code font.

I uninstalled and reinstalled Cascadia Code fonts and Visual Studio was fixed.

**Comment by aaronbell** [comment]
Hi! Sorry for the delay in following up. Please try the new release and let me know if it resolves your issues. Thanks!

https://github.com/microsoft/cascadia-code/releases/tag/v2106.17

**Comment by aaronbell** [comment]
Following up. Did the newer version of the font solve your problem?

**Comment by aaronbell** [comment]
Excellent! Thank you :)

**Comment by aarondglover** [comment]
I have recurrence of this issue today in Visual Studio 2019.
Font Version: CascadiaCode-2108.26

Visual Studio Crashes. When I open a code file I get the "unauthorized" operation error. About to uninstall and reinstall

**Comment by DHowett** [comment]
You are likely experiencing an issue caused by Windows upgrading the Windows Terminal rather than the issue discussed in this bug report. You may want to try to repair the Terminal application instead of reinstalling anything.

The issue reported here does not manifest as the display of any error related to the font file.

**Comment by DHowett** [comment]
@aarondglover ugh, I'm sorry. I misremembered which issue this was -- there is one on our repo where the variable font causes VS on Windows 7 to immediately die without an error message.

It may be worth it to try "repairing" Terminal if you have it installed, but I'm infinitely less confident that that's at all related.
