### ISSUE TITLE
Poor rendering in font dropdown

### ISSUE THREAD

**Issue by GustavBrock** [microsoft/cascadia-code#49]
## Environment

```none
Application (with version) used to display text: Word 365
OS platform and version: Windows 10 1903 Enterprise
```
## Issue

Letters **Æ**, **Ø**, and **Å** must be styled to match **AE**, **O**, and **A** respectively.
For example, compare with these letters from Consolas:

![CascadiaDan](https://user-images.githubusercontent.com/6253835/65235761-8a064000-dad7-11e9-9947-56b3328434b1.PNG)

## Word font menu
Also, rendering of Cascadia's font example in the dropdown in Word is very poor:

![CascadiaWord](https://user-images.githubusercontent.com/6253835/65235837-aace9580-dad7-11e9-8c5e-d39128190f60.PNG)

**Comment by GustavBrock** [comment]
Oh, thanks, I thought the font was ready for international use.
However, that doesn't explain the terrible rendering in the font dropdown.

**Comment by DHowett-MSFT** [comment]
> that doesn't explain ...

Neither does the title of your issue :smile:

I think the dropdown issue is a hinting problem.

**Comment by madig** [comment]
(I think Word's font menu is a special case because it seems to have no anti-aliasing whatsoever, so fonts will only look good if they have been hinted to render fine on Windows 95.)

**Comment by aaronbell** [comment]
Word uses GDI (rather than DWrite) for the font dropdown. As @madig mentions, the font was not hinted for this specific rendering engine in mind as that requires much 'heavier' hinting strategies then is usually required for contemporary OS / screen resolutions. 

Unfortunately, this poor rendering under GDI is true of a lot of fonts, and will continue until Office updates their dropdown.

**Comment by GustavBrock** [comment]
Thanks, @aaronbell. That explains it.
