### ISSUE TITLE
Win7 OTF Install Failed (2105.25)

### ISSUE THREAD

**Issue by WHzhongyixin** [microsoft/cascadia-code#504]
### Cascadia family version

2105.25

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.otf (static)

### Platform

Windows 7 x64

### What happened?

When I Install (2105.24)
CascadiaCodePLItalic-ExtraLightItalic.otf
CascadiaCodePLItalic-SemiBoldItalic.otf
CascadiaCodePLItalic-SemiLightItalic.otf
CascadiaMonoPLItalic-ExtraLightItalic.otf
CascadiaMonoPLItalic-SemiBoldItalic.otf
CascadiaMonoPLItalic-SemiLightItalic.otf
Windows reports that is not valid font.

I wonder if because of the filename too long.

**Comment by aaronbell** [comment]
There's potentially two issues here. One is solved via #466.

The other, like you said, could be due to the length of the file name. Unfortunately, I don't have a Win 7 device, and I don't think that OS is officially supported anymore. 

You might try shortening the file names:
`CascadiaCodePL-EXI.otf`
`CascadiaCodePL-SBI.otf`
`CascadiaCodePL-SLI.otf`
`CascadiaMonoPL-EXI.otf`
`CascadiaMonoPL-SBI.otf`
`CascadiaMonoPL-SLI.otf`

**Comment by WHzhongyixin** [comment]
> There's potentially two issues here. One is solved via #466.
> 
> The other, like you said, could be due to the length of the file name. Unfortunately, I don't have a Win 7 device, and I don't think that OS is officially supported anymore.
> 
> You might try shortening the file names:
> `CascadiaCodePL-EXI.otf`
> `CascadiaCodePL-SBI.otf`
> `CascadiaCodePL-SLI.otf`
> `CascadiaMonoPL-EXI.otf`
> `CascadiaMonoPL-SBI.otf`
> `CascadiaMonoPL-SLI.otf`


Thanks!
I have tried to shorten the file name, but Win 7 still reported the same problem. I will try the new version.
