### ISSUE TITLE
Eclipse code mining: garbled text

### ISSUE THREAD

**Issue by calle2010** [microsoft/cascadia-code#506]
### Cascadia family version

2102.025
2105.024

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable)) (2102.025)
TTF variable as downloaded from GitHub (2105.024)

### Platform

Windows 10

### Other Software

Eclipse 2021-03 (4.19.0)

### What happened?

In Eclipse IDE code mining is rendered with wrong characters:
![image](https://user-images.githubusercontent.com/189960/121518514-dce10300-c9f0-11eb-9baa-a13b78fee9eb.png)
The text should say "2 implementations".

With other fonts I don't see this issue, e. g. Consolas:
![image](https://user-images.githubusercontent.com/189960/121518629-feda8580-c9f0-11eb-9ac1-09132381ea51.png)

I see the issue with Cascadia Code and Cascadia Mono. 
It works fine with Cascadia Code PL and Cascadia Mono PL in older versions (sorry, unknown how old since I uninstalled them, but they didn't have italics).

**Comment by calle2010** [comment]
In an attempt to fix this by installing the latest versions (2105.24) I know have the issue with Cascadia Code PL as well.
I noticed I had old versions of Cascadia Code PL installed that didn't have italics yet.

**Comment by calle2010** [comment]
I don't see the issue with Cascadia Code 2102.03.

**Comment by aaronbell** [comment]
This sort of thing is usually caused by the system not being able to locate the font file as it expects to. And there has been some reworking of the internal name table to account for the addition of the italic variant, so that might be what is going on.

I’d suggest uninstalling all versions of the font, restarting your computer, and reinstalling the latest variable font version.

if that doesn’t work, you may need to [clear the font cache](https://github.com/microsoft/cascadia-code/wiki/Double-installation-issue)

**Comment by aaronbell** [comment]
Hi! Not sure if you're still having troubles, but please try the new release and let me know if it resolves your issues. Thanks!

https://github.com/microsoft/cascadia-code/releases/tag/v2106.17
