### ISSUE TITLE
Ligature for (--) not working

### ISSUE THREAD

**Issue by Muhimen123** [microsoft/cascadia-code#518]
### Cascadia family version

2105.24

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

.ttf (variable)

### Platform

Windows

### Other Software

Visual Studio Code 1.57
Visual Studio Code Insiders 1.58
Pycharm
Windows Terminal
nvim

### What happened?

The ligature for double hyphen is not working in any of my IDE/text editor. I tried reinstalling but the problem keeps occurring again and again. Any ligature other the double hyphen works fine. Here is a gif from my windows terminal. 

![ligatureBug](https://user-images.githubusercontent.com/44261822/122875732-747e1400-d356-11eb-8b37-20bcce1e4cd6.gif)

**Comment by aaronbell** [comment]
Thanks! There actually *is* a ligature there—you can tell because the position of the left-most hyphen shifts a bit to the right when you type the second hyphen. In order for it to become a solid line you have to either enter another `-`, (so `---`) or add another character like `>` `<` `|`. 

The reason why it doesn't become a solid line from the get-go is that `--` has semantic meaning, so it would be confusing not to be able to see both hyphens in that case.
