### ISSUE TITLE
Accented characters break baseline in Excel

### ISSUE THREAD

**Issue by Goldor0ck** [microsoft/cascadia-code#523]
### Cascadia family version

Delivered with Windows Terminal 1.8.1521.0

### Cascadia family variant(s)

Cascadia Code (the version with ligatures)

### Font file format(s)

Windows Terminal included version (TTF (variable))

### Platform

Windows 10 19043.1052

### Other Software

Excel 2105, 14026.20308 Click-to-Run
Windows Terminal 1.8.1521.0

### What happened?

Any accented character (more correctly, with diacritics) breaks the baseline within Excel cells (see below picture).
A quick check shows it doesn't happen on other Office applications
![image](https://user-images.githubusercontent.com/54020541/124147981-7f8c1f00-da8f-11eb-924b-f3247338061a.png)
I saw the problem also occurs on Excel 2016 full version on Windows 10 1809

**Comment by aaronbell** [comment]
Fascinating. Unfortunately, I don't think this is anything that I can fix in the font.

If I had to guess, this is due to the accented characters causing Excel to run the text through the "comprehensive" rendering engine versus the "simple" rendering engine (the simple one is used for simple Latin). As a result, it is catching the 'useTypoMetrics' flag that uses a shorter ascender height instead of using the taller winAscent value. 

Or maybe something else, but it is definitely an Excel issue, unfortunately.
