### ISSUE TITLE
Glyph for arabic numeral 4 seems out of place

### ISSUE THREAD

**Issue by dasMulli** [microsoft/cascadia-code#66]
The glyph for the arabic numeral "4" seems out of place for me as Central European with some exposure to eastern languages (though not speaking any!!).

At first sight, it reminds me of cyrillic glyphs:
<img width="203" alt="image" src="https://user-images.githubusercontent.com/6129250/65272709-decda900-db1f-11e9-9277-8adb29f7d7e9.png">
(The second one is the 4)

Please change the glyph so that the top of the 4 is more closed, creating a more visually closed triangular shape.

**Comment by tabatkins** [comment]
On the other hand, I love the 4 and think it gives character to the font. ^_^

(The "open" 4 is a standard variant, tho it is more common in handwriting; fonts seem to usually prefer the closed 4.)

**Comment by dasMulli** [comment]
If I'm not too mistaken the open 4 the left part pointing to the top is mostly used in English handwriting. That one is different all around the world.. Not entirely against that but then I think it should follow more English handwriting style, like wiring the 1 with just a line etc.

**Comment by tabatkins** [comment]
There I'll disagree on practical grounds - keeping 1, capital-I, and lowercase-l all distinct is more important, especially in a programming font, than any stylistic concerns. ^_^

**Comment by aaronbell** [comment]
Thanks for the feedback! I'm not sure, at this time, there is sufficient need to modify the /4 to create increased differentiation with the Ч or ч. I think the different height of the two vertical strokes, as well as the different heights of the crossbar will help differentiate the different characters. That said, I'll leave this bug open for the time being (especially once the Cyrillic is released!) if others have a similar issue as you. 

As a sneak preview, here's what things look like right now: 
<img width="230" alt="Screen Shot 2019-11-11 at 6 59 02 PM" src="https://user-images.githubusercontent.com/8460297/68638184-92667000-04b5-11ea-954c-a1befd8ceaae.png">

**Comment by Vulgaris-Viridis** [comment]
I guess the thing that makes it stick out even more is that it's the only open character, all other appear to be stylized but "normal". I certainly hope this gets fixed as it is (at least for me personally) highly distracting. The 6 also looks a bit smudged where it connects, but i could get over that, it's definitely less intrusive than the 4. Other than that great job! Really no complains, it looks much, much better than Consolas.

**Comment by aaronbell** [comment]
@dasMulli 

I've been thinking about this 4 some more and have decided to leave it as is.

![main-qimg-7eac605bdcc6dc06663e5705636f7e4b](https://user-images.githubusercontent.com/8460297/72361675-bd806200-36a6-11ea-9904-9d122e48bd07.png)

In handwriting, there's a lot of different ways that people write /4. In the sample above, we have the fully-closed 4, the triangular but disconnected 4, a boxy 4 with curved left-side stroke, and boxy 4 with angled left stroke. In looking around online, I've found even more options—particularly in the cursive sphere. 

In choosing how I wanted to design the /4 for Cascadia Code, I wanted to (a) make sure that it would take up as much white-space in the box as possible, (b) be easily and clearly renderable at small sizes on lower resolutions, and (c) still retaining its 'four'-ness.

Referencing the samples above, the /4 I ended up designing is something of an amalgamation of option 2 and option 4. The more boxy structure helps the /4 use up a lot of the white-space and helps it render more cleanly and clearly, but I made sure that the diagonal was preserved in order to maintain the essence of a /4. 

Also, in your comment on the /y bug report, you mentioned that the /4 shape I chose is particular to the US / Britain. I disagree with that assertion. 

Here's a writing sample from Ethiopia where you can see an open / boxy 4:
![2197409_1429724201 7182_funddescription](https://user-images.githubusercontent.com/8460297/72362452-11d81180-36a8-11ea-991e-61c904f4ecdb.jpg)

Or this graffiti from Brazil:
![59d502479482c image](https://user-images.githubusercontent.com/8460297/72362632-5b286100-36a8-11ea-9922-61402cd9cc57.jpg)

Or these various forms of the 4 in Morocco:
![3](https://user-images.githubusercontent.com/8460297/72363136-2a94f700-36a9-11ea-8b5d-42d956133c80.jpeg)

There's a lot of fours in the world! I completely understand if the one I've created is a bit too handwriting-esque for your tastes, but I still feel that it is the best shape for Cascadia's design.

**Comment by dasMulli** [comment]
Thanks for taking the time for such a detailed explanation @aaronbell, much appreciated!

**Comment by Vulgaris-Viridis** [comment]
@dasMulli I appreciate you thoroughly explaining the reasoning behind your design choice, and while i come from the part of the world where we use the open 4, it is certainly my preferred style - but only when it comes to handwriting. In digital world i prefer clearly defined parameters and uniformity. 

So once again, great style, I'm sure many people will eagerly accept it as the replacement for their current font type, but as with anything many people will also choose to keep the things as they already are. I am one of the latter, 'Consolas' works and as they say if it ain't broke...

**Comment by aaronbell** [comment]
The design is certainly a mix of styles, but not intentionally "American" nor "EU" nor anything. The design is intended for clarity, recognition, and even color. 

Cascadia's 0 is dotted to differentiate from the O, which is difficult to discern in monospaced designs.

Cascadia's 1 is the same as the one you showed. 

Cascadia's 3 is rounded as that helps increase the amount of whitespace in the upper counter, for better clarity at small sizes. 

Cascadia's 7 doesn't have the bar since it would interrupt the upper serif. Certainly I could remove the upper serif in favor of the slash, but I prefer the serif for recognition :). 

In any case, the great thing with fonts is that you can use whatever you prefer!

**Comment by Vulgaris-Viridis** [comment]
> In any case, the great thing with fonts is that you can use whatever you prefer!

That's the one thing we can certainly agree on. Once again, despite my personal preferences, really good job with the font and who knows, maybe it inspires next Luc de Groot to create his own version of it that is more to my liking. 

Though somewhat negative, this is after all only feedback from a limited pool of people who are on GitHub and of those, selected few who are aware of Cascadia's development. Once it exits the beta stage and go mainstream, the feedback will be more accurate.

In any case i applaud the development and this will without doubt be one of the best optional font styles that, I'm sure, many people will use until Microsoft releases update to the Consolas, hopefully with the next major OS revision.

Thank you for your time and once again for the detailed explanation.
